[workspace]
members = [
	"moq-transport",
	"moq-relay-ietf",
	"moq-pub",
	"moq-sub",
	"moq-api",
	"moq-clock-ietf",
	"moq-dir",
	"moq-native-ietf",
	"moq-catalog",
]
resolver = "2"

[patch.crates-io]
# quinn = { git = "https://github.com/Zotyamester/quinn.git", branch = "stop-magic" }
quinn = { path = "../quinn/quinn/" }
# quinn-proto = { git = "https://github.com/Zotyamester/quinn.git", branch = "stop-magic" }
quinn-proto = { path = "../quinn/quinn-proto/" }
web-transport = { path = "../web-transport-rs/web-transport/" }
web-transport-proto = { path = "../web-transport-rs/web-transport-proto/" }
web-transport-quinn = { path = "../web-transport-rs/web-transport-quinn/" }
web-transport-wasm = { path = "../web-transport-rs/web-transport-wasm/" }

[workspace.dependencies]
web-transport = "0.3"
env_logger = "0.11"
log = { version = "0.4", features = ["std"] }

# Use debug symbols in production until things are more stable
[profile.release]
debug = true
