#!/bin/bash
set -euo pipefail

# Change directory to the root of the project
cd "$(dirname "$0")/.."

# Use debug logging by default
export RUST_LOG="${RUST_LOG:-debug}"

# Connect to localhost by default.
HOST1="${HOST1:-localhost}"
HOST2="${HOST2:-localhost}"
PORT1="${PORT1:-4443}"
PORT2="${PORT2:-4444}"
ADDR1="${ADDR1:-$HOST1:$PORT1}"
ADDR2="${ADDR2:-$HOST2:$PORT2}"

# Use the broadcast name "bbb" by default
NAME="${NAME:-bbb}"

# Combine the host and name into URL1 andURL2.
URL1="${URL1:-"https://$ADDR1/$NAME"}"
URL2="${URL2:-"https://$ADDR2/$NAME"}"

cargo run --bin moq-sub -- --name "$NAME" "$URL1" "$URL2" "$@" | ffplay -
